- cleaning
Changed files:
    daemontools.init -> 1.8

diff --git a/daemontools.init b/daemontools.init
--- a/daemontools.init
+++ b/daemontools.init
@@ -19,9 +19,13 @@
 [ -f /etc/sysconfig/svscan ] && . /etc/sysconfig/svscan
 
 # Check that networking is up.
-if is_no "${NETWORKING}"; then
-	msg_network_down svscan
-	exit 1
+if is_yes "${NETWORKING}"; then
+	if [ ! -f /var/lock/subsys/network ]; then
+		msg_network_down svscan
+		exit 1
+	fi
+else
+	exit 0
 fi
 			
 
@@ -40,7 +44,7 @@ case "$1" in
 			RETVAL=0
 		else
 			fail
-			nls "Missing service directory!"
+			echo $(nls "Missing service directory")'!'
 			nls "Create %s first." "$SVSCAN_DIR"
 			RETVAL=1
 		fi
